### ISSUE TITLE
Missing behaviour ?

### ISSUE THREAD

**Issue by jcrombez** [TwoTenPvP/MLAPI-Examples#1]
I think there is a problem with the example project :
![image](https://user-images.githubusercontent.com/777666/38321182-158f2ec4-3837-11e8-8fe4-6f49e03f9f3b.png)

**Comment by TwoTenPvP** [comment]
Yes, this is an issue when unity is importing the DLL. Other have the same problem.

Simply remove missing components and add them manually. The character has a NetworkedObject, NetworkedTransform and a TrackedObject. 

Then a NetworkingManager to the NetworkManager object.

Then it should be fine. I will try to get this sorted asap. Please note that the example contains many outdated things.

**Comment by jcrombez** [comment]
Ok, thank you, at least i got some working networking.

**Comment by TwoTenPvP** [comment]
This should be resolved in the 1.0 version.
